spring.datasource.url=jdbc:postgresql://postgres:5432/carrent
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.mongodb.uri=mongodb://mongo:27017/carrent_docs
spring.mongodb.database=carrent_docs
spring.data.mongodb.gridfs.database=carrent_docs

spring.flyway.url=jdbc:postgresql://postgres:5432/carrent
spring.flyway.user=postgres
spring.flyway.password=postgres

ollama.url=http://ollama:11434
