spring.datasource.url=jdbc:postgresql://postgres:5432/carrent
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.flyway.url=jdbc:postgresql://postgres:5432/carrent
spring.flyway.user=postgres
spring.flyway.password=postgres

ollama.url=http://ollama:11434