ALTER TABLE users
    ADD COLUMN IF NOT EXISTS first_name   VARCHAR(100),
    ADD COLUMN IF NOT EXISTS last_name    VARCHAR(100),
    ADD COLUMN IF NOT EXISTS patronymic   VARCHAR(100),
    ADD COLUMN IF NOT EXISTS birth_date   DATE,
    ADD COLUMN IF NOT EXISTS city         VARCHAR(100),
    ADD COLUMN IF NOT EXISTS country      VARCHAR(100),
    ADD COLUMN IF NOT EXISTS license_path      VARCHAR(500),
    ADD COLUMN IF NOT EXISTS license_status    VARCHAR(30) DEFAULT 'NOT_UPLOADED',
    ADD COLUMN IF NOT EXISTS license_uploaded_at DATE,
    ADD COLUMN IF NOT EXISTS passport_path     VARCHAR(500),
    ADD COLUMN IF NOT EXISTS passport_status   VARCHAR(30) DEFAULT 'NOT_UPLOADED',
    ADD COLUMN IF NOT EXISTS passport_uploaded_at DATE;